updated pre-commit to bypass solhint error in case of no files for linting

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -13,7 +13,7 @@ fi
 echo ""
 echo ""
 echo "Running 'yarn lint-staged' now:"
-yarn lint-staged || true
+yarn lint-staged || echo "No files to lint, but continuing (solhint treats this as error but it's not an error)..."
 
 echo ""
 echo ""
