test

diff --git a/.github/workflows/enforceTestCoverage.yml b/.github/workflows/enforceTestCoverage.yml
--- a/.github/workflows/enforceTestCoverage.yml
+++ b/.github/workflows/enforceTestCoverage.yml
@@ -45,8 +45,11 @@ jobs:
 
       - name: Extract total test coverage
         run: |
+          echo "A"
           # Path to the lcov info file
+          echo "B"
           LCOV_FILE="lcov-filtered.info"
+          echo "C"
 
           # Initialize counters
           total_lines_found=0
@@ -83,15 +86,31 @@ jobs:
           # Calculate percentages with higher precision
           line_coverage_percentage=$(echo "scale=4; $total_lines_hit / $total_lines_found * 100" | bc)
           function_coverage_percentage=$(echo "scale=4; $total_functions_hit / $total_functions_found * 100" | bc)
+          branch_coverage_percentage=$(echo "scale=4; $total_branches_hit / $total_branches_found * 100" | bc)
 
-          # fail if line coverage is less than min value
-          if [[ $LINE_COVERAGE -gt $MIN_TEST_COVERAGE ]]; then
-            echo "Test coverage ($LINE_COVERAGE%) is above min threshold ($MIN_TEST_COVERAGE)"
+          # Output results
+          echo "Line Coverage: $line_coverage_percentage%"
+          echo "Function Coverage: $function_coverage_percentage%"
+          echo "Branch Coverage: $branch_coverage_percentage%"
+
+          # Check against minimum threshold
+          MIN_TEST_COVERAGE=80
+
+          if (( $(echo "$line_coverage_percentage >= $MIN_TEST_COVERAGE" | bc -l) )); then
+              echo "Test coverage ($line_coverage_percentage%) is above min threshold ($MIN_TEST_COVERAGE%)."
           else
-            echo "Test coverage ($LINE_COVERAGE%) is below min threshold ($MIN_TEST_COVERAGE)."
-            echo "Check failed"
-            exit 1
+              echo "Test coverage ($line_coverage_percentage%) is below min threshold ($MIN_TEST_COVERAGE%)."
+              echo "Check failed"
+              exit 1
           fi
+
+      - name: Comment coverage values on PR
+        uses: mshick/add-pr-comment@v2
+        with:
+          message: |
+            TEST COVERAGE:
+            Line Coverage    : $LINE_COVERAGE
+            Function Coverage: $FUNCTION_COVERAGE
 
       # - name: Generate coverage report
       #   run: |
