refactoring

diff --git a/.github/workflows/jsonChecker.yml b/.github/workflows/jsonChecker.yml
--- a/.github/workflows/jsonChecker.yml
+++ b/.github/workflows/jsonChecker.yml
@@ -1,6 +1,6 @@
 name: JSON Checker
-# - checks selected JSON files for semantic issues and fails if any issues are found
-# - validates the following locations/files:
+# - Checks selected JSON files for semantic issues and fails if any issues are found
+# - Validates the following locations/files:
 #   - config/*.json
 #   - deployments/*.json
 #   - audit/auditLog.json
@@ -35,34 +35,42 @@ jobs:
       # Step 4: Find and validate JSON files
       - name: Validate JSON files
         run: |
-
           set -e
 
-          # Function to validate JSON files
+          # Function to validate a single JSON file
+          validate_file() {
+            local file="$1"
+            local max_size=$((5 * 1024 * 1024)) # 5MB limit
+            echo "Validating $file"
+            file_size=$(wc -c < "$file" | tr -d " ")
+
+            # Check if file size is available and numeric
+            if [ -z "$file_size" ] || ! [ "$file_size" -eq "$file_size" ] 2>/dev/null; then
+              echo -e "\033[33mWarning: Unable to determine file size for $file\033[0m"
+            else
+              # Ensure file size does not exceed max limit
+              echo "File size: $file_size"
+              if [ "$file_size" -gt "$max_size" ]; then
+                echo -e "\033[31mError: $file exceeds 5MB limit\033[0m"
+                exit 1
+              fi
+            fi
+
+            # Validate JSON and exit with an error if it fails
+            jsonlint --quiet "$file" || exit 1
+          }
+
+          # Function to validate JSON files in a directory or a single file
           validate_json() {
             local path="$1"
-            # Check if path exists
             if [ -e "$path" ]; then
               echo "Checking $path"
-              # Check if path is a directory
+
               if [ -d "$path" ]; then
+                # If path is a directory, find all JSON files and validate them
                 find "$path" -type f -not -type l -name "*.json" -exec sh -c '
                   for file; do
-                    echo "Validating $file"
-                    # Check file size
-                    file_size=$(wc -c < "$file" | tr -d " ")
-                    if [ -z "$file_size" ] || ! [ "$file_size" -eq "$file_size" ] 2>/dev/null; then
-                      echo -e "\033[33mError: Unable to determine file size for $file\033[0m"
-                    else
-                      # check file size only if its available
-                      echo "file size: $file_size"
-                      if [ "$file_size" -gt '"$max_size"' ]; then
-                        echo -e "\033[31mError: $file exceeds 5MB limit\033[0m"
-                        exit 1
-                      fi
-                    fi
-                    # Validate JSON and exit with error if it fails
-                    jsonlint --quiet "$file" || exit 1
+                    validate_file "$file"
                   done
                 ' sh {} +
               else
@@ -71,18 +79,14 @@ jobs:
                   echo -e "\033[31mError: $path is a symlink\033[0m"
                   exit 1
                 fi
-                # Check file size
-                if [ "$(stat -f%z "$path")" -gt "$max_size" ]; then
-                  echo -e "\033[31mError: $path exceeds 5MB limit\033[0m"
-                  exit 1
-                fi
-                jsonlint --quiet "$path" || exit 1
+                validate_file "$path"
               fi
             else
               echo -e "\033[31mWarning: $path does not exist\033[0m"
             fi
           }
 
+          # Validate JSON files in specified locations
           validate_json "config"
           echo -e "\033[32mAll files in folder config/ validated.\033[0m"
 
@@ -94,3 +98,6 @@ jobs:
 
           validate_json "script/deploy/_targetState.json"
           echo -e "\033[32m_targetState.json validated.\033[0m"
+
+          validate_json "script/deploy/resources/deployRequirements.json"
+          echo -e "\033[32mdeployRequirements.json validated.\033[0m"
