test

diff --git a/.github/workflows/protectAuditFolder.yml b/.github/workflows/protectAuditFolder.yml
--- a/.github/workflows/protectAuditFolder.yml
+++ b/.github/workflows/protectAuditFolder.yml
@@ -20,76 +20,71 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v4
 
-      - name: Verify protected folder changes
+      - name: Get 'Auditors' Team Members
+        env:
+          GH_PAT: ${{ secrets.GIT_TOKEN }}
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
-          echo "Files have been changed in folder audit/** which is a protected folder."
-          echo "Only members of the group 'auditors' are allowed to make changes in this folder."
-          echo "Now checking if the change was done by a member of this group."
-          echo "Checking access permissions for user: ${{ github.actor }}"
 
-          # Verify if the user belongs to the auditors group
-          AUDITORS_GROUP="auditors"
-          AUDITORS=$(curl -s -H "Authorization: token ${{ secrets.GIT_TOKEN }}" https://api.github.com/orgs/lifinance/teams/auditors/members/)
-          USER_GROUP=$(curl -s -H "Authorization: token ${{ secrets.GIT_TOKEN }}" https://api.github.com/orgs/lifinance/teams/auditors/members/${{ github.actor }} | jq -r .login)
+          ##### unset the default git token (does not have sufficient rights to get team members)
+          unset GITHUB_TOKEN
+          ##### use the Personal Access Token to log into git CLI
+          echo $GH_PAT | gh auth login --with-token
+
+          ##### Function that uses github's REST API via CLI to get team members
+          getTeamMembers() {
+            local org=$1
+            local team=$2
+            gh api \
+              -H "Accept: application/vnd.github+json" \
+              -H "X-GitHub-Api-Version: 2022-11-28" \
+              "/orgs/$org/teams/$team/members" | jq -r '.[].login'
+          }
+
+          ORG_NAME="lifinance"
+          TEAM_SLUG="auditors"
+
+          # Get members of each group
+          echo "Fetching members of $TEAM_SLUG..."
+          MEMBERS=$(getTeamMembers $ORG_NAME $TEAM_SLUG)
+
+          #### check if any members were returned
+          if [[ -z $MEMBERS ]]; then
+            echo -e "\033[31mERROR: Could not retrieve team members of group $TEAM_SLUG\033[0m"
+            echo "CONTINUE=false" >> $GITHUB_ENV
+            exit 1
+          fi
+
+          echo "Team members of $TEAM_SLUG: "
+          echo "$MEMBERS"
+
+          echo -e "$MEMBERS" > members.txt
+          echo "CONTINUE=true" >> $GITHUB_ENV
+
+      - name: Verify protected folder changes
+        if: env.CONTINUE == 'true'
+        run: |
+
+
+          echo "Files have been modified in folder 'audit/**' which is a protected folder."
+          echo "Only members of the group 'auditors' are allowed to make changes in this folder."
+          echo "Now checking if user '${{ github.actor }}' is a member of the auditors group"
+          echo "FYI: https://github.com/orgs/lifinance/teams/auditors"
+
+          # load list auditors team members
+          AUDITORS=$(cat members.txt)
 
           echo "AUDITORS:$AUDITORS"
           echo "------------"
-          echo "USER_GROUP:"
-          echo "$USER_GROUP"
 
-          if [ "$USER_GROUP" != "${{ github.actor }}" ]; then
-            echo "User ${{ github.actor }} is not a member of the ${AUDITORS_GROUP} group. Access denied."
-            echo "CONTINUE=false" >> $GITHUB_ENV
-            exit 1
+          #### check if user that submitted the change is indeed part of the auditors group
+          if echo "$USER_GROUP" | grep -wq "${{ github.actor }}"; then
+            echo -e "\033[32mUser ${{ github.actor }} is an auditor and allowed to update the audit folder.\033[0m"
+            echo -e "\033[32mCheck passed.\033[0m"
+            exit 0
           else
-            echo "CONTINUE=true" >> $GITHUB_ENV
-            echo "User ${{ github.actor }} is a member of the ${AUDITORS_GROUP} group. Access granted."
+            echo -e "\031[32mUser ${{ github.actor }} is not an auditor and is not allowed to update the audit folder.\033[0m"
+            echo -e "\031[33mPlease ask an auditor for support.\033[0m"
+            echo -e "\031[32mCheck failed.\033[0m"
+            exit 1
           fi
-
-      # - name: Check if PR has a review by an auditor
-      #   id: check-auditor-approval
-      #   uses: actions/github-script@v7
-      #   if: env.CONTINUE == 'true'
-      #   with:
-      #     script: |
-
-      #       // ANSI escape codes for colors (used for colored output in Git action console)
-      #       const colors = {
-      #         reset: "\033[0m",
-      #         red: "\033[31m",
-      #         green: "\033[32m"
-      #       };
-
-      #       // make sure that reviews are available
-      #       if(!(await github.pulls)) {
-      #         console.log(`${colors.red}Could not get reviewers of this PR from Github. Are there any reviews yet?${colors.reset}`);
-      #         console.log(`${colors.red}Check failed.${colors.reset}`);
-      #         core.setFailed("Required approval is missing");
-      #         return
-      #       }
-
-      #       // get all reviewers of this PR
-      #       const { data: reviews } = await github.pulls.listReviews({
-      #         owner: context.repo.owner,
-      #         repo: context.repo.repo,
-      #         pull_number: context.issue.number,
-      #       });
-
-      #       // Filter to only include reviews that have "APPROVED" status
-      #       const approvedReviews = reviews.filter(review => review.state === 'APPROVED');
-
-      #       // extract the git login handles of all reviewers
-      #       const reviewerHandles = approvedReviews.map(review => review.user.login);
-      #       console.log(`This PR has been reviewed by the following git members: ${reviewerHandles}`)
-
-      #       // check if at least one of these reviewers is member of auditors group
-      #       if (reviewerHandles.some((handle) => coreDevs.includes(handle))) {
-      #         console.log(`${colors.green}The current PR is approved by a member of the $TEAM_SLUG group.${colors.reset}`);
-      #         console.log(`${colors.green}Check passed.${colors.reset}`);
-      #         core.setOutput('approved', 'true');
-      #         } else {
-      #         console.log(`${colors.red}The PR requires a missing approval by a member of the $TEAM_SLUG group.${colors.reset}`);
-      #         console.log(`${colors.red}Find group members here: https://github.com/orgs/lifinance/teams/smart-contract-core.${colors.reset}`);
-      #         console.log(`${colors.red}Check failed.${colors.reset}`);
-      #         core.setFailed("Required approval is missing");
-      #       }
