Added descriptions, removed path to itself in paths hook, updated checkout version. Adde check if Static Analysis has run at least once

diff --git a/.github/workflows/securityAlertsReview.yml b/.github/workflows/securityAlertsReview.yml
--- a/.github/workflows/securityAlertsReview.yml
+++ b/.github/workflows/securityAlertsReview.yml
@@ -1,10 +1,14 @@
 name: Security Alerts Review
 
+# - ensures that all security alerts from olympix static analysis are properly handled before merging.
+# - enforces a strict review policy where every alert must be either resolved or dismissed with a justification.
+# - prevents merging a PR if any alerts are unresolved or dismissed without a comment.
+# - helps maintain a transparent and collaborative security review process by generating a pr comment summarizing the status of all security alerts.
+
 on:
   push:
     paths:
       - 'src/**.sol'
-      - ".github/workflows/securityAlertsReview.yml"
   pull_request:
     types:
       - synchronize
@@ -20,6 +24,37 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
+      # Ensure that the Olympix Static Analysis workflow has run successfully at least once before proceeding.
+      # This check is necessary because the Security Alerts Review workflow should not proceed unless
+      # a valid Olympix Static Analysis report is available for the current branch.
+      - name: Check if Olympix Static Analysis has run at least once and was successful
+        id: check-analysis
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          BRANCH_NAME: ${{ github.head_ref }}
+        run: |
+
+          # Fallback in case BRANCH_NAME is empty.
+          if [ -z "$BRANCH_NAME" ]; then
+            BRANCH_NAME="${GITHUB_HEAD_REF:-${GITHUB_REF##*/}}"
+            echo "BRANCH_NAME was empty, falling back to: $BRANCH_NAME"
+          fi
+
+          echo "Checking latest Olympix Static Analysis run for branch: $BRANCH_NAME"
+
+          # Fetch the latest completed runs of the Olympix Static Analysis workflow
+          LATEST_RUN=$(curl -s -H "Authorization: token ${GITHUB_TOKEN}" \
+            "https://api.github.com/repos/${{ github.repository }}/actions/workflows/olympixStaticAnalysis.yml/runs?status=completed&per_page=10")
+
+          # Filter to find the first run with head_branch matching our branch name
+          WORKFLOW_STATUS=$(echo "$LATEST_RUN" | jq -r --arg branch "$BRANCH_NAME" '.workflow_runs[] | select(.head_branch == $branch) | .conclusion' | head -n1)
+
+          if [[ "$WORKFLOW_STATUS" != "success" ]]; then
+            echo "The Olympix Static Analysis workflow has not been successfully completed for branch: $BRANCH_NAME."
+            echo "The Security Alerts Review workflow cannot continue because a valid Olympix Static Analysis report is required."
+            exit 1
+          fi
+
       - name: Fetch PR Number
         id: fetch_pr
         env:
