test

diff --git a/.github/workflows/verifyAudit.yml b/.github/workflows/verifyAudit.yml
--- a/.github/workflows/verifyAudit.yml
+++ b/.github/workflows/verifyAudit.yml
@@ -15,12 +15,14 @@ on:
     types: [opened, synchronize, reopened]
 
 jobs:
-  check-if-audit-required:
+  verify-audit:
     # will only run once the PR is in "Ready for Review" state
     if: ${{ github.event.pull_request.draft == false }}
     runs-on: ubuntu-latest
     env:
       GITHUB_TOKEN: ${{ secrets.GIT_ACTIONS_BOT_PAT_CLASSIC }}
+      AUDIT_LOG_PATH: 'audit/auditLog.json'
+
     permissions:
       pull-requests: write
     steps:
@@ -29,8 +31,8 @@ jobs:
         with:
           fetch-depth: 0 ##### Fetch all history for all branches
 
-      - name: Check PR for changes for protected folders ('src/*')
-        id: check_if_audit_is_required
+      - name: Check PR for changes in protected folders ('src/*')
+        id: check_git_diff_for_protectected_folders
         run: |
 
 
@@ -132,18 +134,131 @@ jobs:
               console.log(`${colors.green}Verified that exactly one label is assigned. Check passed :)${colors.reset}`);
             }
 
-  verify-audit-information:
-    needs: check-if-audit-required # This job will run only after the audit check completes successfully
-    runs-on: ubuntu-latest
-    env:
-      auditLogPath: 'audit/auditLog.json'
-    permissions:
-      pull-requests: write
-    steps:
-      - name: Check if audit is required
+      - name: Verify Audit Log
+        id: verify-audit-log
+        if: env.AUDIT_REQUIRED == 'true'
         run: |
 
           # load list of protected contracts
-          AUDIT_REQUIRED=$(cat audit_required.txt)
+          PROTECTED_CONTRACTS=$(cat protected_contracts.txt)
 
-          echo "Audit Required: ($AUDIT_REQUIRED)"
+          # create temp files to store commit hashes and auditor handles
+          COMMIT_HASHES_FILE="commit_hashes.txt"
+          AUDITOR_GIT_HANDLES_FILE="auditor_handles.txt"
+
+          ##### make sure that there are any protected contracts
+          if [[ -z $PROTECTED_CONTRACTS ]]; then
+            echo -e "\033[31mNo protected contracts found. This should not happen (action should stop earlier). Please check the code of the Github action. Aborting now.\033[0m"
+            echo "CONTINUE=false" >> $GITHUB_ENV
+            exit 1
+          fi
+
+          # iterate through all contracts
+          while IFS= read -r FILE; do
+            # load contract version
+            VERSION=$(sed -nE 's/^\/\/\/ @custom:version ([0-9]+\.[0-9]+\.[0-9]+).*/\1/p' "$FILE")
+
+            ##### make sure that contract version was extracted successfully
+            if [[ -z $VERSION ]]; then
+              echo -e "\033[31mCould not find version of contract $FILE. This should not happen. Please check the Github action code. Aborting now.\033[0m"
+              echo "CONTINUE=false" >> $GITHUB_ENV
+              exit 1
+            fi
+
+            # see if audit log contains an entry with those values
+            FILENAME=$(basename "$FILE" .sol)
+
+            LOG_ENTRIES=$(jq -r --arg filename "$FILENAME" --arg version "$VERSION" '.[$filename][$version][]' "$auditLogPath")
+
+            ##### make sure that audit log entries were found
+            if [[ -z $LOG_ENTRIES || "${#LOG_ENTRIES}" -eq 0 ]]; then
+              echo -e "\033[31mCould not find a logged audit for contract $FILENAME in version $VERSION.\033[0m"
+              echo -e "\033[31mThis github action cannot complete until the audit log contains a logged audit for this file.\033[0m"
+              echo "CONTINUE=false" >> $GITHUB_ENV
+              exit 1
+            fi
+
+            # Iterate through all log entries
+            echo "$LOG_ENTRIES" | jq -c '.' | while IFS= read -r entry; do
+              # extract log entry values into variables
+              AUDIT_COMPLETED_ON=$(echo "$entry" | jq -r '.auditCompletedOn')
+              AUDITED_BY=$(echo "$entry" | jq -r '.auditedBy')
+              AUDITOR_GIT_HANDLE=$(echo "$entry" | jq -r '.auditorGitHandle')
+              AUDIT_REPORT_PATH=$(echo "$entry" | jq -r '.auditReportPath')
+              AUDIT_COMMIT_HASH=$(echo "$entry" | jq -r '.auditCommitHash')
+
+              # make sure that audit log entry contains date
+              if [ -z "$AUDIT_COMPLETED_ON" ]; then
+                echo -e "\033[31mThe audit log entry for file $FILE contains an invalid or no 'auditCompletedOn' date.\033[0m"
+                echo -e "\033[31mThis github action cannot complete before the audit log is complete.\033[0m"
+                echo -e "\033[31mAborting now.\033[0m"
+                echo "CONTINUE=false" >> $GITHUB_ENV
+                exit 1
+              fi
+
+              # make sure that audit log entry contains auditor's (company) name
+              if [ -z "$AUDITED_BY" ]; then
+                echo -e "\033[31mThe audit log entry for file $FILE contains invalid or no 'auditedBy' information.\033[0m"
+                echo -e "\033[31mThis github action cannot complete before the audit log is complete.\033[0m"
+                echo -e "\033[31mAborting now.\033[0m"
+                echo "CONTINUE=false" >> $GITHUB_ENV
+                exit 1
+              fi
+
+              # make sure that audit log entry contains auditor's git handle
+              if [ -z "$AUDITOR_GIT_HANDLE" ]; then
+                echo -e "\033[31mThe audit log entry for file $FILE contains invalid or no 'auditorGitHandle' information.\033[0m"
+                echo -e "\033[31mThis github action cannot complete before the audit log is complete.\033[0m"
+                echo -e "\033[31mAborting now.\033[0m"
+                echo "CONTINUE=false" >> $GITHUB_ENV
+                exit 1
+              fi
+
+
+              # make sure that audit log entry contains audit report path
+              if [ -z "$AUDIT_REPORT_PATH" ]; then
+                echo -e "\033[31mThe audit log entry for file $FILE contains invalid or no 'auditReportPath' information.\033[0m"
+                echo -e "\033[31mThis github action cannot complete before the audit log is complete.\033[0m"
+                echo -e "\033[31mAborting now.\033[0m"
+                echo "CONTINUE=false" >> $GITHUB_ENV
+                exit 1
+              fi
+
+              # make sure that a file exists at the audit report path
+              if [ ! -f "$AUDIT_REPORT_PATH" ]; then
+                echo -e "\033[31mCould not find an audit report in path $AUDIT_REPORT_PATH for contract "$FILENAME".\033[0m"
+                echo -e "\033[31mThis github action cannot complete before the audit report is uploaded to 'audit/reports/'.\033[0m"
+                echo -e "\033[31mAborting now.\033[0m"
+                echo "CONTINUE=false" >> $GITHUB_ENV
+                exit 1
+              fi
+
+              # make sure that audit log entry contains audit report path
+              if [ -z "$AUDIT_COMMIT_HASH" ]; then
+                echo -e "\033[31mThe audit log entry for file $FILE contains invalid or no 'auditCommitHash' information.\033[0m"
+                echo -e "\033[31mThis github action cannot complete before the audit log is complete.\033[0m"
+                echo -e "\033[31mAborting now.\033[0m"
+                echo "CONTINUE=false" >> $GITHUB_ENV
+                exit 1
+              fi
+
+              # store the commit hash in a temporary file to check its validity in a following step
+              # echo "$AUDIT_COMMIT_HASH" >> "$COMMIT_HASHES_FILE"
+              echo "$AUDIT_COMMIT_HASH" >> commit_hashes.txt
+
+              # store the auditor git handle to check it in a following step if this auditor has reviewed the PR
+              # echo "$AUDITOR_GIT_HANDLE" >> "$AUDITOR_GIT_HANDLES_FILE"
+              echo "$AUDITOR_GIT_HANDLE" >> auditor_handles.txt
+            done
+          done <<< "$PROTECTED_CONTRACTS"
+
+          echo -e "\033[32mAll audit log entries are complete.\033[0m"
+
+
+          # # read the temp files into variables
+          # AUDIT_COMMIT_HASHES=$(cat "$COMMIT_HASHES_FILE" | tr '\n' ' ')
+          # AUDITOR_GIT_HANDLES=$(cat "$AUDITOR_GIT_HANDLES_FILE" | tr '\n' ' ')
+          # echo "AUDIT_COMMIT_HASHES=$AUDIT_COMMIT_HASHES"
+          # echo "AUDIT_COMMIT_HASHES=$AUDIT_COMMIT_HASHES" >> $GITHUB_ENV
+          # echo "AUDITOR_GIT_HANDLES=$AUDITOR_GIT_HANDLES"
+          # echo "AUDITOR_GIT_HANDLES=$AUDITOR_GIT_HANDLES" >> $GITHUB_ENV
