test

diff --git a/.github/workflows/versionCheck.yml b/.github/workflows/versionCheck.yml
--- a/.github/workflows/versionCheck.yml
+++ b/.github/workflows/versionCheck.yml
@@ -145,6 +145,8 @@ jobs:
         env:
           PR_TITLE: ${{github.event.pull_request.title}}
         run: |
+
+
           echo "PR_TITLE: $PR_TITLE"
 
           echo "-----------------------------------"
@@ -165,9 +167,21 @@ jobs:
               echo "PR title contains target string '$TARGET_STRING'"
             else
               echo "PR title does not contain target string '$TARGET_STRING'"
-              PR_TITLE_UPDATED=""$PR_TITLE_UPDATED""$TARGET_STRING","
+              PR_TITLE_UPDATED=""$PR_TITLE_UPDATED""$TARGET_STRING", "
             fi
           done
+
+          # Check if the last two characters are ", "
+          if [[ "${PR_TITLE_UPDATED: -2}" == ", " ]]; then
+            # Remove the last two characters and append a closing bracket
+            PR_TITLE_UPDATED="${PR_TITLE_UPDATED:0:-2})"
+          elif [[ "${PR_TITLE_UPDATED: -1}" == "(" ]]; then
+            # Remove the last character if it is an open bracket
+            PR_TITLE_UPDATED="${PR_TITLE_UPDATED:0:-1}"
+          else
+            echo "Error: Unexpected ending in PR_TITLE_UPDATED: '$PR_TITLE_UPDATED'"
+            exit 1
+          fi
 
           echo "Final PR Title: $PR_TITLE_UPDATED)"
           echo "PR_TITLE=$PR_TITLE_UPDATED" >> $GITHUB_ENV
