test

diff --git a/.github/workflows/versionCheck.yml b/.github/workflows/versionCheck.yml
--- a/.github/workflows/versionCheck.yml
+++ b/.github/workflows/versionCheck.yml
@@ -63,9 +63,19 @@ jobs:
           # Check for missing version updates
           while IFS= read -r FILE; do
             if [[ "$FILE" == *.sol ]]; then
+              # extract the version from the contract
               VERSION_TAG=$(grep -E '^/// @custom:version' "$FILE" || true)
               VERSION=$(grep -E '^/// @custom:version' <filename> | sed -E 's/^.*/// @custom:version ([0-9]+\.[0-9]+\.[0-9]+).*$/\1/' || true)
               echo "File: $FILE   ||  Version: $VERSION_TAG   || Version: $VERSION"
+
+              # make sure version was extracted successfully
+              if [[ -z "$VERSION" ]];
+                echo "Could not extract contract version from contract $FILE. Please check if the contract is OK, otherwise there is a problem in this Github action"
+                exit 1
+              fi
+
+              # if version is available but was not updated
+
               if [[ -n "$VERSION_TAG" ]] && ! git diff -U0 origin/${BASE_REF} HEAD "$FILE" | grep -qE '^@@.*\+/// @custom:version'; then
                 MISSING_VERSION_UPDATE+=("$FILE")
               fi
